routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/swagger-doc', 'SwaggerController@index')->name('swagger');
Route::get('/swagger-redoc', 'SwaggerController@redoc')->name('swagger.redoc');
Route::get('/swagger-doc/app.yaml', 'SwaggerController@getYaml')->name('swagger.yaml');

Route::group(['middleware' => 'auth:admins'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('admins', 'AdminController', ['except' => ['show']]);
    Route::put('admins/{admin}/password', ['as' => 'admins.password', 'uses' => 'AdminController@password']);

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::get('users', 'UserController@index')->name('users.index');
    Route::post('users/{user}/toggle-active', 'UserController@toggleActive')->name('users.toggle-active');

    Route::resource('tariffs', 'TariffController', ['except' => ['show']]);

    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    Route::get('transactions/csv', 'TransactionController@toCsv')->name('transactions.csv');

    Route::get('statistics', 'StatisticController@index')->name('statistics.index');
    Route::post('statistics/fetch', 'StatisticController@fetch')->name('statistics.fetch');
    Route::get('statistics/csv', 'StatisticController@toCsv')->name('statistics.csv');

    Route::get('rebills', 'RebillController@index')->name('rebills.index');

    Route::get('feedback', 'FeedbackController@index')->name('feedbacks.index');

    Route::get('cohort-analysis', 'CohortController@index')->name('cohort.index');
    Route::post('cohort-analysis', 'CohortController@index')->name('cohort.index');
});

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/blue.png" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('images') }}/admin-avatar.png">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('Profile') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admins.index') }}">
                        <i class="ni ni-circle-08" style="color: #f4645f;"></i> Admin Management
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('users.index') }}">
                        <i class="ni ni-circle-08 text-primary"></i> User Management
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tariffs.index') }}">
                        <i class="ni ni-money-coins text-primary"></i> Tariffs
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('transactions.index') }}">
                        <i class="ni ni-watch-time text-primary"></i> Transactions
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('statistics.index') }}">
                        <i class="ni ni-chart-bar-32 text-primary"></i> Statistics
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('cohort.index') }}">
                        <i class="ni ni-chart-bar-32 text-primary"></i> Cohort
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('rebills.index') }}">
                        <i class="ni ni-credit-card text-primary"></i> Rebills Forecast
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('feedbacks.index') }}">
                        <i class="ni ni-bulb-61 text-primary"></i> Feedback
                    </a>
                </li>
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading -->
        </div>
    </div>
</nav>