routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/swagger-doc', 'SwaggerController@index')->name('swagger');
Route::get('/swagger-redoc', 'SwaggerController@redoc')->name('swagger.redoc');
Route::get('/swagger-doc/app.yaml', 'SwaggerController@getYaml')->name('swagger.yaml');

Route::group(['middleware' => 'auth:admins'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('admins', 'AdminController', ['except' => ['show']]);
    Route::put('admins/{admin}/password', ['as' => 'admins.password', 'uses' => 'AdminController@password']);

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::get('users', 'UserController@index')->name('users.index');
    Route::post('users/{user}/toggle-active', 'UserController@toggleActive')->name('users.toggle-active');

    Route::resource('tariffs', 'TariffController', ['except' => ['show']]);

    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    Route::get('transactions/csv', 'TransactionController@toCsv')->name('transactions.csv');

    Route::get('statistics', 'StatisticController@index')->name('statistics.index');
    Route::post('statistics/fetch', 'StatisticController@fetch')->name('statistics.fetch');
    Route::get('statistics/csv', 'StatisticController@toCsv')->name('statistics.csv');

    Route::get('rebills', 'RebillController@index')->name('rebills.index');

    Route::get('feedback', 'FeedbackController@index')->name('feedbacks.index');

    Route::get('cohort-analysis', 'CohortController@index')->name('cohort.index');
    Route::post('cohort-analysis', 'CohortController@index')->name('cohort.index');
});

app/Models/Feedback.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class Feedback
 *
 * @property int    $id
 * @property int    $user_id
 * @property int    $rate
 * @property string $text
 *
 * @property Carbon $created_at
 * @property Carbon $updated_at
 *
 * @package App\Models
 */

class Feedback extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'rate', 'text',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use phpDocumentor\Reflection\Types\Boolean;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class User
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property string $os_version
 * @property string $ip
 * @property string $country
 * @property string $city
 * @property string $connection
 * @property string $proxy_type
 * @property boolean $is_active
 * @property int $tariff_id
 * @property int $paid_until
 * @property float $payment_amount
 * @property string $tariff_list
 * @property string $push_token
 * @property int $notification_status
 * @property Carbon $notificated_at
 * @property string $version
 * @property integer $screen
 *
 * @property Carbon $created_at
 * @property Carbon $updated_at
 *
 * @package App\Models
 */

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username',
        'password',
        'os_version',
        'ip',
        'country',
        'city',
        'connection',
        'proxy_type',
        'is_active',
        'tariff_id',
        'paid_until',
        'payment_amount',
        'tariff_list',
        'screen',
    ];

    protected $perPage = 50;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'notificated_at',
    ];

    /**
     * Route notifications for the mail channel.
     *
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return array|string
     */
    public function routeNotificationForMail($notification)
    {
        return $this->username;
    }

    // Rest omitted for brevity

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function transactions(): HasMany
    {
        return $this->hasMany(Transaction::class);
    }

    public function getIsPaidAttribute(): Bool
    {
        if ($this->transactions()->count()) {
            return true;
        }
        return false;
    }

    public function scopeHasPaid(Builder $query): Builder
    {
        return $query->has('transactions');
    }

    public function getShortUsername(): string
    {
        return substr($this->username, 0, 8);
    }
}

resources/views/feedback/index.blade.php
@extends('layouts.app', ['title' => __('Feedback list')])

@section('content')
    @include('layouts.headers.partials.header', [
       'title' => 'Users feedback',
       'description' => __('This is list of users feedback.'),
       'class' => 'col-lg-12'
   ])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-md-12">
                                <h3 class="mb-0">Feedback list</h3>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">User ID</th>
                                <th scope="col">Is user paid</th>
                                <th scope="col">Rate</th>
                                <th scope="col">Text</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($feedbacks as $feedback)
                                <tr>
                                    <td>{{ $feedback->user->id }}</td>
                                    <td>
                                        @if ($feedback->user->is_paid)
                                            <span class="badge badge-pill badge-success">Yes</span>
                                        @else
                                            <span class="badge badge-pill badge-danger">No</span>
                                        @endif
                                    </td>
                                    <td>{{ $feedback->rate }}</td>
                                    <td>{{ $feedback->text }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        {{ $feedbacks->withQueryString()->links('layouts.pagination.bootstrap-4') }}
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection